plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Metrics/ClassLength:
  Exclude:
    - "spec/**/*"
Metrics/MethodLength:
  Exclude:
    - "spec/**/*"
RSpec/MultipleExpectations:
  Max: 2
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
