# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: plissken 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "plissken"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dave Hrycyszyn", "Michael Chrisco"]
  s.date = "2014-12-31"
  s.description = "\n    Have you ever needed to automatically convert JSON-style camelBack or\n    CamelCase hash keys into more Rubyish snake_case?\n\n    Plissken to the rescue.\n\n    This gem recursively converts all camelBack or CamelCase keys in a hash\n    structure to snake_case.\n  "
  s.email = "dave.hrycyszyn@headlondon.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/plissken.rb",
    "lib/plissken/ext/hash/to_snake_keys.rb",
    "plissken.gemspec",
    "spec/lib/to_snake_keys_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb",
    "test/plissken/ext/hash/to_snake_keys_test.rb",
    "test/test_plissken.rb"
  ]
  s.homepage = "http://github.com/futurechimp/plissken"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Snakify your camel keys when working with JSON APIs"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<symbolize>, ["~> 4.2"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.6"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
    else
      s.add_dependency(%q<symbolize>, ["~> 4.2"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.6"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<symbolize>, ["~> 4.2"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.6"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
  end
end

