name: Generate Changelog

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: ardalanamini/auto-changelog@d1bf07e4b9aa751c458406bb50fc9908929c9b86
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat: Features
            fix: Bug Fixes
            docs: Documentation
            perf: Performance
            refactor: Refactoring
            test: Testing
            ci: CI/CD
            chore: skip
          default-commit-type: Other

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b
        with:
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
